### ISSUE TITLE
Keep getting an error even when changing the model to gpt-3.5-turbo

### ISSUE THREAD

**Issue by gbstan** [mattvr/ShellGPT#1]
Even after changing the model to gpt-3.5-turbo using `gpt --config`. I am using MacOS  13.3.1

I keep getting this error:

```
Failed to parse message TypeError: Failed to parse message:
"{
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
"
```

**Comment by gbstan** [comment]
Further information: I have an OpenAI API Key and have set this up via `export OPENAI_API_KEY=...`

**Comment by gbstan** [comment]
This command works: `gpt --fast "What is the meaning of life, the universe, and everything?"`
but the command `gpt "What is the meaning of life, the universe, and everything?"` throws the error above for some reason.

**Comment by nmarks99** [comment]
I'm having the same issue

**Comment by mattvr** [comment]
Sorry about this, should be fixed now.

@gbstan @nmarks99 can you install the latest version and let me know if it fixed via:

`deno install -frA --name=gpt https://deno.land/x/shellgpt/mod.ts`

**Comment by nmarks99** [comment]
Yep it's fixed, thanks!
