### ISSUE TITLE
Feature request: Able to log the answers of the gpt commands

### ISSUE THREAD

**Issue by soderluk** [mattvr/ShellGPT#24]
One thing that I've been missing with this, is that once I get an answer from the gpt command, and I accidentally close the terminal, I lose the answer to my question. Even if I run the same question again, it might be different from the previous good one.

Would it be possible to add the answer to the history as well? Now `gpt --history` just lists all the previous questions. The `gpt --dump` only shows the last answer, but if I'd want to show a specific answer from the history, is that possible? If not, would it be possible to implement, something like `gpt --dump <history_entry>` -> `gpt --dump 2023-09-15_11-37-14`?

Now that I look at the history, the entries are in descending order, i.e. the latest entry is on top, which makes me scroll all the way back up in the terminal. This should probably be in ascending order, so the latest question is visible at the bottom of the list.

Thoughts on these?

**Comment by soderluk** [comment]
Testing this a bit more, I found out that I can use `gpt --dump --name "2023-09-15_11-37-14"` but that specific use-case is not documented in the README.

**Comment by mattvr** [comment]
@soderluk You might actually want to use `gpt -p` for this case. `-p` prints the last response again.
