### ISSUE TITLE
configure removal of wpm limitation

### ISSUE THREAD

**Issue by ekg** [mattvr/ShellGPT#6]
It's a little unclear to me why you'd want to throttle the output to a given wpm. Is there a way to configure this limit to be "off"?

**Comment by mattvr** [comment]
@ekg the purpose is to make the output appear smooth. Most GPT tools have choppy output that comes in chunks of words. I found that aesthetically less pleasing than character-by-character streaming.

You could alias gpt to `gpt --wpm 9999 $@` in your shell's profile to avoid the throttling. I could also add a permanent config setting for it in the next update.

**Comment by ekg** [comment]
Thanks, I understand that. From my perspective these interfaces are useful in an environment that is unlikely to be observed by a human, so simulating human behavior is irrelevant. I can do the alias of course. Does setting the wpm value to a huge number ensure the flow is as fast as possible?

**Comment by mattvr** [comment]
@ekg I've added the ability to bypass the WPM buffered output:
- You can now pass a `--wpm` value less than 0 (e.g. `--wpm=-1`). This will bypass the buffer and output as fast as possible.
- You can also configure this permanently by manually editing your `$HOME/.gpt/config.json` and adding an line for `"wpm": -1`

Relevant release notes and update instructions are here: https://github.com/mattvr/ShellGPT/releases/tag/0.3.1

Thanks for the feedback and let me know if you have any issues or further suggestions.
